Project4: CSS3 Flexbox & Grid
3rkeen/New-York-Times-Clone pull request #1
Opened 2020-03-05 20:17 UTC by 3rkeen

This project is completed by using CSS flexbox and grid

2020-03-06 04:10 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @3rkeen and @Jmagero :balloon: :lollipop: 

### Good job so far, the page looks very similar to the original and your CSS file it's optimal :ok_hand: there is still some work to be done :construction: :construction_worker_woman: :construction_worker_man:  please address the comments I've made in your code and next :point_down: 

## Page structure and Implementation details

#### Navigation bar

- [ ] It should have a fixed position and all the elements (menu, search icon, space and cosmos link, new york times logo, and buttons) should be links or have a pointer when hovered

![image](https://user-images.githubusercontent.com/52209067/76048245-dc72d600-5f2a-11ea-8cd0-fed23e35ec8d.png)

#### The theory of inflation

- [ ] you are missing the [theory of inflation background image](https://static01.nyt.com/newsgraphics/2014/03/18/theory-of-inflation/1ebaa1b972edda0f407fbaa0e010f6b50fb6792e/inflation-945.png) let's add it 

![image](https://user-images.githubusercontent.com/52209067/76048377-44c1b780-5f2b-11ea-9060-86e39a8cf259.png)

#### Bottom part

* [ ] It contains links (`<a>` tags that show a pointer when hovered) to More in Space and Astronomy and Editor's pics with image previews on the leftmost side. 
* [ ] It contains links (`<a>` tags that show a pointer when hovered) to most popular articles on the rightmost side. 
* [ ] you have More in Space and Astronomy title repeated 2 times the bottom one should be change to Editor's picks

#### Footer

- [ ] Add the footer bar that the page has when the user is not logged in and this should have a fixed position 

![image](https://user-images.githubusercontent.com/52209067/76050215-4c359080-5f2c-11ea-852f-9c2f021de8de.png)

## General

#### Descriptive pull request

- [ ] Edit your pull request to explain more about what you did in the project, one line is not enough let's add a couple more

#### In line styling

- [ ] I found inline styling in your code so please address the comment I've left bellow :arrow_double_down: 

### That's it, team! :raised_hands: 

### Please :pray: do the changes :woman_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-03-06 04:10 UTC, euqueme commented on index.html
> +        ></iframe>
- [ ] move the width and height from the iframe to a class in the CSS file since no inline styling is allowed in the HTML file

2020-03-06 15:51 UTC, 3rkeen commented
Dear  Maria,

Please check the updated version of the project where all the errors has
been corrected.

Thank you.

On Fri, Mar 6, 2020 at 6:10 AM Maria Eugenia Quemé Peña <
notifications@github.com> wrote:

> *@euqueme* requested changes on this pull request.
>
> Pull Request under the review by Maria Eugenia Queme P. (TSE)
>
> Hello @3rkeen <https://github.com/3rkeen> and @Jmagero
> <https://github.com/Jmagero> 🎈 🍭 Good job so far, the page looks very
> similar to the original and your CSS file it's optimal 👌
>
> there is still some work to be done 🚧 👷‍♀ : 👷 please address the
> comments I've made in your code and next 👇
> Page structure and Implementation details Navigation bar
>
>    - It should have a fixed position and all the elements (menu, search
>    icon, space and cosmos link, new york times logo, and buttons) should be
>    links or have a pointer when hovered
>
> [image: image]
> <https://user-images.githubusercontent.com/52209067/76048245-dc72d600-5f2a-11ea-8cd0-fed23e35ec8d.png>
> The theory of inflation
>
>    - you are missing the theory of inflation background image
>    <https://static01.nyt.com/newsgraphics/2014/03/18/theory-of-inflation/1ebaa1b972edda0f407fbaa0e010f6b50fb6792e/inflation-945.png>
>    let's add it
>
> [image: image]
> <https://user-images.githubusercontent.com/52209067/76048377-44c1b780-5f2b-11ea-9060-86e39a8cf259.png>
> Bottom part
>
>    - It contains links (<a> tags that show a pointer when hovered) to
>    More in Space and Astronomy and Editor's pics with image previews on the
>    leftmost side.
>    - It contains links (<a> tags that show a pointer when hovered) to
>    most popular articles on the rightmost side.
>    - you have More in Space and Astronomy title repeated 2 times the
>    bottom one should be change to Editor's picks
>
> Footer
>
>    - Add the footer bar that the page has when the user is not logged in
>    and this should have a fixed position
>
> [image: image]
> <https://user-images.githubusercontent.com/52209067/76050215-4c359080-5f2c-11ea-852f-9c2f021de8de.png>
> General Descriptive pull request
>
>    - Edit your pull request to explain more about what you did in the
>    project, one line is not enough let's add a couple more
>
> In line styling
>
>    - I found inline styling in your code so please address the comment
>    I've left bellow ⏬
>
> That's it, team! 🙌 Please 🙏 do the changes 👩‍💻 👨‍💻 and submit back
> for a code review when you are done 📝
>
> Happy coding! 🚀
>
> Any questions? ask me on slack *@ Maru*
>
> PROJECT STATUS: REQUESTED CHANGES 🚦
> ------------------------------
>
> In index.html
> <https://github.com/3rkeen/New-York-Times-Clone/pull/1#discussion_r388702767>
> :
>
> > +        <iframe
>
> +          width="600"
>
> +          height="319"
>
> +          src="https://www.youtube.com/embed/ZlfIVEy_YOA"
>
> +          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
>
> +          allowfullscreen
>
> +        ></iframe>
>
>
>
>    - move the width and height from the iframe to a class in the CSS file
>    since no inline styling is allowed in the HTML file
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/3rkeen/New-York-Times-Clone/pull/1?email_source=notifications&email_token=AGEGSZ6GN52DVMED6FSDKZ3RGBZUXA5CNFSM4LCRYE7KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCYHNDRA#pullrequestreview-370069956>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGEGSZYAJ7DQAV4ADKIHNOLRGBZUXANCNFSM4LCRYE7A>
> .
>

2020-03-06 19:00 UTC, uryelah commented
Hello **Jocyline Magero** & **Erkin Sheraliev**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Good job fixing the changes from the last cr 🎇 🎆 **
There's still some work to be done so that your project is good to go, so hang in there.

---------    

**Great job at: 🥇** 
- positioning the main text of the page
- using semantic HTML
- using icons at the start of the article
- paying attention to text color

**You still need to fix the issues below before you can move to the next project**

---------

### Required changes 🛠 

- [ ] Like the last TSE pointed out, the **More in space and Astronomy** and **Editor Picks** recommended articles are all clickable, have the pointer cursor when you hover over them, and not only the text, **the images are also clickable**. 
[Check the original site for reference.](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

- [ ] Good job adding the 'Theory of Inflation' Images but take some time to fix the font-weight also. Compare your version and the original one bellow.
![Screenshot_2020-03-06 Document](https://user-images.githubusercontent.com/16193212/76113557-23140f00-5fc3-11ea-8642-66f7326724f0.png)
![Screenshot_2020-03-06 Space Ripples Reveal Big Bang’s Smoking Gun(1)](https://user-images.githubusercontent.com/16193212/76113559-24ddd280-5fc3-11ea-8634-2faa13d14a08.png)


- [ ] Please add icons to the Subscribe area of the footer. Compare your version and the original one bellow:

![Screenshot_2020-03-06 Document(1)](https://user-images.githubusercontent.com/16193212/76113678-58b8f800-5fc3-11ea-9a7d-58a460043f3a.png)
![Screenshot_2020-03-06 Space Ripples Reveal Big Bang’s Smoking Gun(2)](https://user-images.githubusercontent.com/16193212/76113681-59ea2500-5fc3-11ea-826a-54aa22f9f93b.png)

- [ ] Fix your **Most Popular** links so they have the same font size and margin as the original ones.

---------
### Optional Enhancements

- [ ] The original site has a lot of nice hover effects. Why not add them too?
---------
 
**Please fix the required changes 👷  before asking for a new code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-06 20:52 UTC, 3rkeen commented
Dear Sarah,

We have fixed all the issues you mentioned. Please check.

Thank you.

On Fri, Mar 6, 2020 at 9:00 PM Sarah Chamorro <notifications@github.com>
wrote:

> Hello *Jocyline Magero* & *Erkin Sheraliev*, I'm Sarah, your reviewer for
> this PR 👩‍🚀
>
> **Good job fixing the changes from the last cr 🎇 🎆 **
> There's still some work to be done so that your project is good to go, so
> hang in there.
> ------------------------------
>
> *Great job at: 🥇*
>
>    - positioning the main text of the page
>    - using semantic HTML
>    - using icons at the start of the article
>    - paying attention to text color
>
> *You still need to fix the issues below before you can move to the next
> project*
> ------------------------------
> Required changes 🛠
>
>    -
>
>    Like the last TSE pointed out, the *More in space and Astronomy* and *Editor
>    Picks* recommended articles are all clickable, have the pointer cursor
>    when you hover over them, and not only the text, *the images are also
>    clickable*.
>    Check the original site for reference.
>    <https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html>
>    -
>
>    Good job adding the 'Theory of Inflation' Images but take some time to
>    fix the font-weight also. Compare your version and the original one bellow.
>    [image: Screenshot_2020-03-06 Document]
>    <https://user-images.githubusercontent.com/16193212/76113557-23140f00-5fc3-11ea-8642-66f7326724f0.png>
>    [image: Screenshot_2020-03-06 Space Ripples Reveal Big Bang’s Smoking
>    Gun(1)]
>    <https://user-images.githubusercontent.com/16193212/76113559-24ddd280-5fc3-11ea-8634-2faa13d14a08.png>
>    -
>
>    Please add icons to the Subscribe area of the footer. Compare your
>    version and the original one bellow:
>
> [image: Screenshot_2020-03-06 Document(1)]
> <https://user-images.githubusercontent.com/16193212/76113678-58b8f800-5fc3-11ea-9a7d-58a460043f3a.png>
> [image: Screenshot_2020-03-06 Space Ripples Reveal Big Bang’s Smoking
> Gun(2)]
> <https://user-images.githubusercontent.com/16193212/76113681-59ea2500-5fc3-11ea-826a-54aa22f9f93b.png>
>
>    - Fix your *Most Popular* links so they have the same font size and
>    margin as the original ones.
>
> ------------------------------
> Optional Enhancements
>
>    - The original site has a lot of nice hover effects. Why not add them
>    too?
>
> ------------------------------
>
> *Please fix the required changes 👷 before asking for a new code review*
> ------------------------------
>
> Cheers and Happy coding!👏👏👏
>
> Code review by *Sarah Uryelah Silva Chamorro*
>
> (Feel free to contact me on slack by the handle of *sarah* if you have
> any additional question)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/3rkeen/New-York-Times-Clone/pull/1?email_source=notifications&email_token=AGEGSZY2GRXCUWDOH6NADDLRGFB3HA5CNFSM4LCRYE7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOCOLJA#issuecomment-595912100>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGEGSZ5HE2VNXO5WFIO6R43RGFB3HANCNFSM4LCRYE7A>
> .
>

2020-03-07 00:29 UTC, SofiBretz commented
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] 'Editor's Pick' i overlapping with the main text, consider to fix this as the original page:

![1](https://user-images.githubusercontent.com/42303392/76132297-fe369080-5ff0-11ea-972b-044524892c28.PNG)

![1 1](https://user-images.githubusercontent.com/42303392/76132305-0b537f80-5ff1-11ea-8d28-5368fabb524a.PNG)

- [ ] Social icons should be a link, consider check the original page social icons to see that they are links to click.

[OPTIONAL]

- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

- [ ] Consider adding the new version on your 'demo link' in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

2020-03-09 00:45 UTC, majovanilla commented
Great work team!! :star: 

You made all the required changes and you are able to merge.

Status: **approved**

2020-03-09 15:28 UTC, merged